package com.devgyu.banchan.alarm;

public enum AlarmType {
    ORDER_ACCEPTED, ORDER_REJECTED, DELIVERY_START, COMPLETED, RIDER_ORDER_ACCEPT,
    STORE_ACCEPTED, STORE_REJECTED, RIDER_ACCEPTED, RIDER_REJECTED
}
