spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/banchan
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  servlet:
    session:
      timeout: 60m

app:
  host: http://localhost:8080
  uploadFolderPrefix: /Users/devgyu/banchan

spring.jackson.default-property-inclusion: NON_NULL

logging:
  level:
    org:
      hibernate:
        stat: debug
#        type: trace


