spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/banchan
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

app:
  host: http://localhost:8080
  uploadFolderPrefix: /Users/devgyu/banchan

logging:
  level:
    org:
      hibernate:
        stat: debug
#        type: trace